linters-settings:
  govet:
    check-shadowing: true
  maligned:
    suggest-new: true
  dupl:
    threshold: 200
  goconst:
    min-len: 3
    min-occurrences: 2
  forbidigo:
    forbid:
      - ^print.*$
      - 'fmt\.Print.*'
  gocognit:
    min-complexity: 65 # This is super high value. We should gradually lower it to 30-40.

linters:
  enable:
    - gosec
  disable:
    - typecheck
    - errcheck
    - govet
    - staticcheck
    - gosimple
    - deadcode
    - gofmt
    - goimports
    - bodyclose
    - dupl
    #- forbidigo # <- see later
    - gocognit
    - gocritic
    - goimports
    - nakedret
    #- nolintlint
    - revive
    - stylecheck
    - unconvert
    - unparam
    - maligned
    - lll
    - gochecknoinits
    - gochecknoglobals
issues:
  exclude-rules:
    - linters:
      - revive
      text: "var-naming"
    - linters:
      - revive
      text: "type name will be used as (.+?) by other packages, and that stutters"
    - linters:
      - stylecheck
      text: "ST1003"
