package fixhandler

import (
	"context"
	"encoding/json"
	"errors"
	"fmt"
	"io"
	"math"
	"os"
	"path/filepath"
	"reflect"
	"regexp"
	"sort"
	"strconv"
	"strings"

	"github.com/armosec/armoapi-go/armotypes"
	"github.com/kubescape/go-logger"
	"github.com/kubescape/go-logger/helpers"
	"github.com/kubescape/k8s-interface/workloadinterface"
	"github.com/kubescape/kubescape/v4/core/cautils"
	metav1 "github.com/kubescape/kubescape/v4/core/meta/datastructures/v1"
	"github.com/kubescape/opa-utils/objectsenvelopes"
	"github.com/kubescape/opa-utils/objectsenvelopes/localworkload"
	"github.com/kubescape/opa-utils/reporthandling"
	"github.com/kubescape/opa-utils/reporthandling/results/v1/resourcesresults"
	reporthandlingv2 "github.com/kubescape/opa-utils/reporthandling/v2"
	storagev1beta1 "github.com/kubescape/storage/pkg/apis/softwarecomposition/v1beta1"
	"github.com/mikefarah/yq/v4/pkg/yqlib"
	"gopkg.in/op/go-logging.v1"
	"gopkg.in/yaml.v3"
)

const UserValuePrefix = "YOUR_"

const windowsNewline = "\r\n"
const unixNewline = "\n"
const oldMacNewline = "\r"

func NewFixHandler(fixInfo *metav1.FixInfo) (*FixHandler, error) {
	if info, err := os.Stat(fixInfo.ReportFile); err == nil && info.IsDir() {
		return nil, fmt.Errorf("%q is a directory, not a file. Please provide a JSON report file path", fixInfo.ReportFile)
	}
	jsonFile, err := os.Open(fixInfo.ReportFile)
	if err != nil {
		return nil, err
	}
	defer jsonFile.Close()
	byteValue, err := io.ReadAll(jsonFile)
	if err != nil {
		return nil, fmt.Errorf("failed to read report file: %w", err)
	}

	var reportObj reporthandlingv2.PostureReport
	if err = json.Unmarshal(byteValue, &reportObj); err != nil {
		// Heuristic: if the file looks like YAML rather than JSON, give the
		// user a clearer message than the raw json decoder error.
		trimmed := strings.TrimPrefix(string(byteValue), "\ufeff")
		trimmed = strings.TrimLeft(trimmed, " \t\r\n")
		if !strings.HasPrefix(trimmed, "{") && !strings.HasPrefix(trimmed, "[") {
			return nil, fmt.Errorf("%q does not look like a kubescape JSON scan report. Run `kubescape scan --format json --output <file>` first and pass that file to `kubescape fix`", fixInfo.ReportFile)
		}
		return nil, fmt.Errorf("failed to parse %q as a kubescape JSON scan report: %w", fixInfo.ReportFile, err)
	}

	if err = validateReportStructure(byteValue, &reportObj); err != nil {
		return nil, err
	}

	if err = isSupportedScanningTarget(&reportObj); err != nil {
		return nil, err
	}

	// A cluster report has no local root: its resources are live objects, never
	// files. Both checks below exist to locate and constrain manifests on disk,
	// so neither has anything to act on — and getLocalPath returns "" for a
	// cluster target, which would fail the stat outright.
	var localPath string
	if !isClusterReport(&reportObj) {
		localPath = getLocalPath(&reportObj)
		if _, err = os.Stat(localPath); err != nil {
			return nil, err
		}

		// localPath comes straight out of the report (RepoContextMetadata.LocalRootPath /
		// DirectoryContextMetadata.BasePath / dirname(FileContextMetadata.FilePath)), which
		// is untrusted input if fixInfo.ReportFile came from somewhere the caller doesn't
		// fully control. By default we still trust it, exactly as before - kubescape fix
		// has no other way to know where a report's files live. If the caller passed
		// --base-path, though, require the report's claimed location to actually resolve
		// inside it before accepting it as the fix root.
		if fixInfo.BasePath != "" {
			resolvedLocalPath, err := filepath.EvalSymlinks(localPath)
			if err != nil {
				return nil, fmt.Errorf("failed to resolve report's scan path %q: %w", localPath, err)
			}
			resolvedBasePath, err := filepath.EvalSymlinks(fixInfo.BasePath)
			if err != nil {
				return nil, fmt.Errorf("invalid --base-path %q: %w", fixInfo.BasePath, err)
			}
			if !isPathContained(resolvedBasePath, resolvedLocalPath) {
				return nil, fmt.Errorf("report's scan path %q is outside --base-path %q; refusing to trust the report's location claim", localPath, fixInfo.BasePath)
			}
		}
	}

	backendLoggerLeveled := logging.AddModuleLevel(logging.NewLogBackend(logger.L().GetWriter(), "", 0))
	backendLoggerLeveled.SetLevel(logging.ERROR, "")
	yqlib.GetLogger().SetBackend(backendLoggerLeveled)

	return &FixHandler{
		fixInfo:       fixInfo,
		reportObj:     &reportObj,
		localBasePath: localPath,
	}, nil
}

const invalidReportFileErr = "invalid report file: not a valid kubescape scan report. Please provide a JSON file generated by 'kubescape scan --format json'"

func validateReportStructure(raw []byte, report *reporthandlingv2.PostureReport) error {
	if hasSupportedLocalContext(report) {
		return nil
	}
	// Recognize cluster/remote reports (scanMetadata can be empty since Cluster is enum 0 + omitempty) so isSupportedScanningTarget returns the precise error
	if hasRecognizedScanContext(report) {
		return nil
	}
	if looksLikeKubescapeReport(raw) {
		return nil
	}
	return errors.New(invalidReportFileErr)
}

// hasRecognizedScanContext reports whether the report carries any known context metadata type (Cluster, Repo, File, Directory, or Helm)
func hasRecognizedScanContext(report *reporthandlingv2.PostureReport) bool {
	ctx := report.Metadata.ContextMetadata
	return ctx.ClusterContextMetadata != nil ||
		ctx.RepoContextMetadata != nil ||
		ctx.FileContextMetadata != nil ||
		ctx.DirectoryContextMetadata != nil ||
		ctx.HelmContextMetadata != nil
}

func hasSupportedLocalContext(report *reporthandlingv2.PostureReport) bool {
	switch report.Metadata.ScanMetadata.ScanningTarget {
	case reporthandlingv2.GitLocal:
		return report.Metadata.ContextMetadata.RepoContextMetadata != nil &&
			report.Metadata.ContextMetadata.RepoContextMetadata.LocalRootPath != ""
	case reporthandlingv2.Directory:
		return report.Metadata.ContextMetadata.DirectoryContextMetadata != nil &&
			report.Metadata.ContextMetadata.DirectoryContextMetadata.BasePath != ""
	case reporthandlingv2.File:
		return report.Metadata.ContextMetadata.FileContextMetadata != nil &&
			report.Metadata.ContextMetadata.FileContextMetadata.FilePath != ""
	default:
		return false
	}
}

func looksLikeKubescapeReport(raw []byte) bool {
	var shape struct {
		Metadata       json.RawMessage `json:"metadata"`
		GenerationTime json.RawMessage `json:"generationTime"`
		SummaryDetails json.RawMessage `json:"summaryDetails"`
		Results        json.RawMessage `json:"results"`
		Resources      json.RawMessage `json:"resources"`
		Attributes     json.RawMessage `json:"attributes"`
	}
	if err := json.Unmarshal(raw, &shape); err != nil {
		return false
	}
	if len(shape.Metadata) == 0 {
		return false
	}
	// Require a non-empty scanMetadata object, but don't gate on scanningTarget
	var metaShape struct {
		ScanMetadata map[string]json.RawMessage `json:"scanMetadata"`
	}
	if err := json.Unmarshal(shape.Metadata, &metaShape); err != nil || len(metaShape.ScanMetadata) == 0 {
		return false
	}
	return len(shape.GenerationTime) > 0 ||
		len(shape.SummaryDetails) > 0 ||
		len(shape.Results) > 0 ||
		len(shape.Resources) > 0 ||
		len(shape.Attributes) > 0
}

func isSupportedScanningTarget(report *reporthandlingv2.PostureReport) error {
	scanningTarget := report.Metadata.ScanMetadata.ScanningTarget
	if scanningTarget == reporthandlingv2.GitLocal || scanningTarget == reporthandlingv2.Directory || scanningTarget == reporthandlingv2.File {
		return nil
	}
	// A cluster scan records live objects rather than manifests, so there is
	// nothing on disk to rewrite. Those resources are patched in memory and the
	// result is emitted for the user to apply, so the report is still usable.
	if isClusterReport(report) {
		return nil
	}

	return fmt.Errorf("unsupported scanning target. Supported scanning targets are: a cluster, a local git repo, a directory or a file")
}

// isClusterReport reports whether the report came from a live-cluster scan, in
// which case no resource has a file on disk and every fix is rendered from the
// scanned object instead.
//
// The cluster context metadata is part of the test, not decoration. Cluster is
// the zero value of ScanningTarget and the field is tagged omitempty, so a
// report that never had a scanningTarget — a truncated file, a hand-rolled
// document, a report from a tool that writes the enum differently —
// deserializes as a cluster scan. Every real cluster scan records its context
// (cautils.setContextMetadata, and OPASessionObj fills it in unconditionally),
// so requiring it keeps those malformed reports on the "unsupported scanning
// target" error they returned before rather than being quietly accepted as an
// empty cluster scan that reports nothing to fix.
func isClusterReport(report *reporthandlingv2.PostureReport) bool {
	return report != nil &&
		report.Metadata.ScanMetadata.ScanningTarget == reporthandlingv2.Cluster &&
		report.Metadata.ContextMetadata.ClusterContextMetadata != nil
}

func (h *FixHandler) isClusterReport() bool {
	return isClusterReport(h.reportObj)
}

// IsClusterReport reports whether the loaded report came from a live-cluster
// scan, so the caller knows to render manifests with RenderFixes rather than
// rewrite files with ApplyChanges.
func (h *FixHandler) IsClusterReport() bool {
	return h.isClusterReport()
}

func getLocalPath(report *reporthandlingv2.PostureReport) string {
	if report == nil {
		return ""
	}
	switch report.Metadata.ScanMetadata.ScanningTarget {
	case reporthandlingv2.GitLocal:
		if repo := report.Metadata.ContextMetadata.RepoContextMetadata; repo != nil {
			return repo.LocalRootPath
		}
		return ""
	case reporthandlingv2.Directory:
		return report.Metadata.ContextMetadata.DirectoryContextMetadata.BasePath
	case reporthandlingv2.File:
		return cautils.FileScanRootPath(report.Metadata.ContextMetadata.FileContextMetadata.FilePath)
	default:
		return ""
	}
}

// resourceBasePath returns the root the resource's relative path resolves against. The
// resource's own Source.Path is the root the scan computed that relative path from, so
// it stays correct where the report-wide base path does not: multi-input scans record
// only the first input, and a single-file scan records the file rather than its root. In
// both, Source.Path is an ancestor of the report-wide path rather than a descendant.
//
// Only an absolute root is accepted: the scanner always records one, and a relative value
// would resolve against the process working directory rather than anything in the report.
// Reports without a usable root (cloned repos, older reports) keep using the report-wide
// path. Traversal is contained where it can actually occur, on the join in
// PrepareResourcesToFix.
//
// Source.Path is as report-supplied as the report-wide path, so --base-path has to
// constrain it too: without this it would be the one way a report could still name a fix
// root outside the anchor the caller vouched for.
func (h *FixHandler) resourceBasePath(resourceObj *reporthandling.Resource) string {
	if resourceObj == nil || resourceObj.Source == nil {
		return h.localBasePath
	}
	sourcePath := resourceObj.Source.Path
	if sourcePath == "" || !filepath.IsAbs(sourcePath) {
		return h.localBasePath
	}
	if h.fixInfo != nil && h.fixInfo.BasePath != "" && !isPathContained(h.fixInfo.BasePath, sourcePath) {
		logger.L().Debug("ignoring resource source path outside --base-path",
			helpers.String("sourcePath", sanitizeForLog(sourcePath)), helpers.String("basePath", h.fixInfo.BasePath))
		return h.localBasePath
	}
	return sourcePath
}

// countResourcesPerFile tallies every resource the scan read from each manifest,
// keyed by the file the report recorded it against.
func (h *FixHandler) countResourcesPerFile(resources map[string]*reporthandling.Resource) map[string]int {
	perFile := make(map[string]int, len(resources))
	for _, resource := range resources {
		if key := h.resourceFileKey(resource); key != "" {
			perFile[key]++
		}
	}
	return perFile
}

// resourceFileKey is the manifest a resource was read from, without the
// document index the report appends to it.
func (h *FixHandler) resourceFileKey(resource *reporthandling.Resource) string {
	if resource == nil {
		return ""
	}
	filePath, _, err := h.getFilePathAndIndex(h.getPathFromRawResource(resource.GetObject()))
	if err != nil {
		return ""
	}
	return filePath
}

func (h *FixHandler) buildResourcesMap() map[string]*reporthandling.Resource {
	resourceIdToRawResource := make(map[string]*reporthandling.Resource)
	for i := range h.reportObj.Resources {
		resourceIdToRawResource[h.reportObj.Resources[i].GetID()] = &h.reportObj.Resources[i]
	}
	for i := range h.reportObj.Results {
		if h.reportObj.Results[i].RawResource == nil {
			continue
		}
		resourceIdToRawResource[h.reportObj.Results[i].RawResource.GetID()] = h.reportObj.Results[i].RawResource
	}

	return resourceIdToRawResource
}

func (h *FixHandler) getPathFromRawResource(obj map[string]any) string {
	if localworkload.IsTypeLocalWorkload(obj) {
		localwork := localworkload.NewLocalWorkload(obj)
		return localwork.GetPath()
	} else if objectsenvelopes.IsTypeRegoResponseVector(obj) {
		regoResponseVectorObject := objectsenvelopes.NewRegoResponseVectorObject(obj)
		relatedObjects := regoResponseVectorObject.GetRelatedObjects()
		for _, relatedObject := range relatedObjects {
			if localworkload.IsTypeLocalWorkload(relatedObject.GetObject()) {
				return relatedObject.(*localworkload.LocalWorkload).GetPath()
			}
		}
	}

	return ""
}

// resourceSource is where a resource's YAML can be read from and written back
// to. It is resolved once per resource, ahead of any expression building, so
// that a resource the fixer cannot touch is identified before any work is done
// on it.
type resourceSource struct {
	// filePath is the manifest to patch, already resolved against the
	// resource's own base path and containment-checked. Empty when skipReason
	// is set.
	filePath string
	// documentIndex is the resource's position within a multi-document file.
	documentIndex int
	// reportedPath is the raw path the report recorded for this resource. It is
	// kept separately from filePath because the user-facing skip entry needs it
	// even on the paths where resolution never produced a filePath.
	reportedPath string
	// inMemory marks a resource with no manifest on disk, patched by rendering
	// the scanned object instead of rewriting a file.
	inMemory bool
	// skipReason, when non-empty, means this resource cannot be fixed. The
	// caller re-reports the resource's failed controls as unfixed rather than
	// dropping them.
	skipReason string
}

// redactedContentReason reports why a resource's recorded copy is not a
// faithful one, or "" when it is.
//
// A scan report is built for reporting, not for round-tripping. Before results
// are aggregated, updateResults calls removeData over every resource
// (opaprocessor/processorhandlerutils.go), which for a workload replaces every
// container env value with "XXXXXX" and drops valueFrom/envFrom, and for a
// Secret or ConfigMap redacts data/stringData. Rendering a manifest from such a
// copy would hand the user YAML that overwrites their real configuration with
// the redaction placeholder — verified against a real cluster, where the two
// DaemonSets carrying env vars came back with "value": "XXXXXX".
//
// The file scan path is unaffected because it patches the manifest on disk and
// only reads the report to decide which edits to make. The cluster path has no
// file, so it has to decline these instead.
//
// Everything else removeData strips — the last-applied annotation,
// managedFields and status — this package removes deliberately anyway, so a
// resource that passes this check is byte-faithful in every field that matters.
//
// Known gap: a container using only envFrom is undetectable here, because
// envFrom is deleted outright rather than replaced with a marker. Such a
// manifest is incomplete rather than wrong, and `kubectl apply` on a resource
// with no last-applied annotation does not delete fields the config omits, so
// the live envFrom survives.
func redactedContentReason(obj map[string]any) string {
	switch kind, _ := obj["kind"].(string); kind {
	case "Secret", "ConfigMap":
		return "skipped: scan reports redact this resource's data, so a rendered manifest would not be faithful"
	}

	workload := workloadinterface.NewWorkloadObj(obj)
	if workload == nil {
		return ""
	}

	const envRedacted = "skipped: scan reports redact container environment variables, so a rendered manifest would overwrite them"

	if containers, err := workload.GetContainers(); err == nil {
		for i := range containers {
			if len(containers[i].Env) > 0 || len(containers[i].EnvFrom) > 0 {
				return envRedacted
			}
		}
	}
	if initContainers, err := workload.GetInitContainers(); err == nil {
		for i := range initContainers {
			if len(initContainers[i].Env) > 0 || len(initContainers[i].EnvFrom) > 0 {
				return envRedacted
			}
		}
	}
	if ephemeral, err := workload.GetEphemeralContainers(); err == nil {
		for i := range ephemeral {
			if len(ephemeral[i].Env) > 0 || len(ephemeral[i].EnvFrom) > 0 {
				return envRedacted
			}
		}
	}

	return ""
}

// hasOwnerReferences reports whether a Kubernetes object is managed by another
// resource.
func hasOwnerReferences(obj map[string]any) bool {
	metadata, ok := obj["metadata"].(map[string]any)
	if !ok {
		return false
	}
	owners, ok := metadata["ownerReferences"].([]any)
	return ok && len(owners) > 0
}

// resolveClusterResourceSource handles a resource from a live-cluster scan.
// There is no manifest to locate, so the only question is whether the recorded
// object is something a manifest can be rendered from.
func (h *FixHandler) resolveClusterResourceSource(resourceObj *reporthandling.Resource) resourceSource {
	obj := resourceObj.GetObject()

	// A RegoResponseVector is a rule's finding over several related objects
	// (RBAC bindings, cloud configuration), not one addressable resource, so
	// there is no single manifest to emit for it.
	if objectsenvelopes.IsTypeRegoResponseVector(obj) {
		return resourceSource{skipReason: "skipped: not a single patchable workload"}
	}

	// Without both of these the rendered YAML is not a manifest anything could
	// apply, so emitting it would be worse than saying nothing.
	apiVersion, _ := obj["apiVersion"].(string)
	kind, _ := obj["kind"].(string)
	if apiVersion == "" || kind == "" {
		return resourceSource{skipReason: "skipped: resource is not a complete Kubernetes object"}
	}

	// A resource owned by another cannot be patched where it stands, so emitting
	// a manifest for it would hand the user something that does not apply. The
	// owner recreates it from its own template, and for a Pod the API server
	// rejects nearly every spec change outright:
	//
	//	pod updates may not change fields other than `spec.containers[*].image` ...
	//
	// Static control-plane pods are the sharpest case — owned by the Node and
	// rendered by the kubelet from files on it. Verified against a real kind
	// cluster, where kubectl refused exactly these four.
	//
	// This checks ownerReferences directly rather than using
	// k8sinterface.WorkloadHasParent, which returns false for a Pod that plainly
	// has an owner and so would not catch this.
	if hasOwnerReferences(obj) {
		return resourceSource{skipReason: "skipped: managed by another resource; fix its owner instead"}
	}

	// Last, because it is the most expensive check and the least likely to fire.
	if reason := redactedContentReason(obj); reason != "" {
		return resourceSource{skipReason: reason}
	}

	// documentIndex stays 0: a rendered resource is always a single document,
	// which is what the select(di==0) in the fix expressions addresses.
	return resourceSource{inMemory: true}
}

// resolveResourceSource decides where a resource's YAML lives, or why it cannot
// be reached: a local manifest for a file-based scan, or the scanned object
// itself for a cluster scan.
func (h *FixHandler) resolveResourceSource(ctx context.Context, resourceObj *reporthandling.Resource) resourceSource {
	if h.isClusterReport() {
		return h.resolveClusterResourceSource(resourceObj)
	}

	src := resourceSource{
		reportedPath: h.getPathFromRawResource(resourceObj.GetObject()),
	}

	// Determine an upfront reason if we already know this resource is not
	// fixable, so we can still surface its failed controls as "unfixed".
	if src.reportedPath == "" {
		src.skipReason = "skipped: resource has no local file path"
		return src
	}
	if resourceObj.Source == nil || !isFixableSourceType(resourceObj.Source.FileType) {
		src.skipReason = "skipped: source is not a YAML or JSON file"
		return src
	}

	relativePath, idx, err := h.getFilePathAndIndex(src.reportedPath)
	if err != nil {
		logger.L().Ctx(ctx).Warning("Skipping invalid resource path: " + sanitizeForLog(src.reportedPath))
		src.skipReason = "skipped: invalid resource path"
		return src
	}

	// the resource's own root, not the report-wide one: a single-file
	// scan records the file rather than its root, and a multi-input
	// scan records only the first input. relativePath is report input
	// and is the field that can carry "..", so the file this package
	// writes to must still land inside the root it resolved against.
	basePath := h.resourceBasePath(resourceObj)
	candidatePath := filepath.Join(basePath, relativePath)
	if _, err := os.Stat(candidatePath); err != nil {
		// Checked before containment so EvalSymlinks (inside
		// isPathContained) has something to resolve, and so a
		// missing file is reported as such rather than as
		// "escapes scanned directory".
		logger.L().Ctx(ctx).Warning("Skipping missing file: " + sanitizeForLog(candidatePath))
		src.skipReason = "skipped: file not found"
		return src
	}
	if !isPathContained(basePath, candidatePath) {
		logger.L().Ctx(ctx).Warning("Skipping resource path that escapes the scanned directory: " + sanitizeForLog(src.reportedPath))
		src.skipReason = "skipped: resource path escapes scanned directory"
		return src
	}

	src.filePath = candidatePath
	src.documentIndex = idx
	return src
}

// PrepareResourcesToFix returns the YAML-source resources that the existing
// yq-based pipeline can patch. Helm-rendered resources are split off into
// PrepareHelmSuggestions because their fix paths reference rendered output
// that has no reliable line mapping back to the source template.
func (h *FixHandler) PrepareResourcesToFix(ctx context.Context) []ResourceFixInfo {
	resourceIdToResource := h.buildResourcesMap()

	resourcesToFix := make([]ResourceFixInfo, 0)
	resourcesPerFile := h.countResourcesPerFile(resourceIdToResource)
	h.unfixedControls = h.unfixedControls[:0]
	h.fixedControlsCount = 0

	var containerProfile *storagev1beta1.ContainerProfile
	if h.fixInfo != nil && h.fixInfo.ContainerProfilePath != "" {
		profileData, err := os.ReadFile(h.fixInfo.ContainerProfilePath)
		if err == nil {
			var cp storagev1beta1.ContainerProfile
			if err := json.Unmarshal(profileData, &cp); err == nil {
				containerProfile = &cp
			} else {
				logger.L().Ctx(ctx).Warning("Failed to unmarshal container profile: " + sanitizeForLog(err.Error()))
			}
		} else {
			logger.L().Ctx(ctx).Warning("Failed to read container profile: " + sanitizeForLog(err.Error()))
		}
	}

	for _, result := range h.reportObj.Results {
		if !result.GetStatus(nil).IsFailed() {
			continue
		}

		resourceID := result.ResourceID
		resourceObj := resourceIdToResource[resourceID]
		if resourceObj == nil {
			// The report references a resource ID with no backing resource data.
			// We cannot fix it, but it is still a failed control the user must
			// remediate manually — surface it rather than dropping it.
			logger.L().Ctx(ctx).Warning("Skipping result with no resource data in report: " + sanitizeForLog(resourceID))
			for i := range result.AssociatedControls {
				ac := &result.AssociatedControls[i]
				if !ac.GetStatus(nil).IsFailed() {
					continue
				}
				h.unfixedControls = append(h.unfixedControls, UnfixedControl{
					ControlID:    ac.GetID(),
					ControlName:  ac.GetName(),
					ResourceName: resourceID,
					Reason:       "skipped: resource data missing from report",
				})
			}
			continue
		}
		src := h.resolveResourceSource(ctx, resourceObj)

		if src.skipReason != "" {
			for i := range result.AssociatedControls {
				ac := &result.AssociatedControls[i]
				if !ac.GetStatus(nil).IsFailed() {
					continue
				}
				h.unfixedControls = append(h.unfixedControls, UnfixedControl{
					ControlID:    ac.GetID(),
					ControlName:  ac.GetName(),
					ResourceName: resourceObj.GetName(),
					ResourceKind: resourceObj.GetKind(),
					FilePath:     sanitizeForLog(src.reportedPath),
					Reason:       src.skipReason,
				})
			}
			continue
		}

		// Where an unfixed control gets reported as living. A cluster resource
		// has no path, and leaving it empty renders as "<unknown>", which reads
		// like the fixer lost track of the resource rather than the resource
		// simply having no file.
		location := sanitizeForLog(src.filePath)
		if src.inMemory {
			location = "cluster"
		}

		rfi := ResourceFixInfo{
			FilePath:        src.filePath,
			fileKey:         h.resourceFileKey(resourceObj),
			Resource:        resourceObj,
			YamlExpressions: make(map[string]armotypes.FixPath, 0),
			DocumentIndex:   src.documentIndex,
			inMemory:        src.inMemory,
		}

		// Tentative unfixed entries for this resource. We collect them locally
		// so a post-loop reconciliation pass can promote controls whose failed
		// paths are covered by another control's planned YamlExpressions.
		type pendingUnfixed struct {
			entry UnfixedControl
			ac    *resourcesresults.ResourceAssociatedControl
		}
		var tentativeUnfixed []pendingUnfixed

		for i := range result.AssociatedControls {
			ac := &result.AssociatedControls[i]
			if !ac.GetStatus(nil).IsFailed() {
				continue
			}

			added, skipped := rfi.addYamlExpressionsFromResourceAssociatedControl(src.documentIndex, ac, h.fixInfo.SkipUserValues)

			rfi.failedControls = append(rfi.failedControls, UnfixedControl{
				ControlID:    ac.GetID(),
				ControlName:  ac.GetName(),
				ResourceName: resourceObj.GetName(),
				ResourceKind: resourceObj.GetKind(),
				FilePath:     location,
			})

			// Fully auto-remediated: every failed path produced an expression.
			if added > 0 && len(skipped) == 0 {
				h.fixedControlsCount++
				rfi.fixedCount++
				continue
			}

			// Partial or fully unfixed — surface as needing manual work. The
			// concrete fixes (if any) are still applied via rfi.YamlExpressions,
			// but the control is not counted as fully fixed because rules under
			// it remain unaddressed.
			reason := "no auto-fix available for this control"
			if len(skipped) > 0 {
				reason = skipped[0]
			}
			if added > 0 {
				reason = "partial: " + reason
			}
			tentativeUnfixed = append(tentativeUnfixed, pendingUnfixed{
				entry: UnfixedControl{
					ControlID:    ac.GetID(),
					ControlName:  ac.GetName(),
					ResourceName: resourceObj.GetName(),
					ResourceKind: resourceObj.GetKind(),
					FilePath:     location,
					Reason:       reason,
				},
				ac: ac,
			})
		}

		// Reconcile tentative-unfixed entries against the final set of planned
		// YamlExpressions for this resource: a control's failed paths may be
		// covered by another control's FixPath (e.g. C-0016's
		// "privileged = false" also remediates C-0057). Promote those to
		// fixed instead of misleading the user with "no auto-fix available".
		plannedPaths := plannedPathsFromExpressions(rfi.YamlExpressions)
		for _, pu := range tentativeUnfixed {
			if len(plannedPaths) > 0 && controlIsCoveredByPlannedPaths(pu.ac, plannedPaths) {
				h.fixedControlsCount++
				rfi.fixedCount++
				continue
			}
			h.unfixedControls = append(h.unfixedControls, pu.entry)
		}

		if containerProfile != nil {
			var rawManifest []byte
			if resourceObj != nil && resourceObj.GetObject() != nil {
				rawManifest, _ = json.Marshal(resourceObj.GetObject())
			}

			var workloadKind string
			var containerName string

			if resourceObj != nil {
				workloadKind = resourceObj.GetKind()
			}

			// Verify resourceObj matches containerProfile's workload labels
			labels := containerProfile.GetLabels()
			profileMatches := true
			if labels != nil {
				containerName = labels["kubescape.io/workload-container-name"]
				profileKind := labels["kubescape.io/workload-kind"]
				profileName := labels["kubescape.io/workload-name"]
				profileNamespace := labels["kubescape.io/workload-namespace"]

				if resourceObj != nil {
					if profileKind != "" && !strings.EqualFold(profileKind, resourceObj.GetKind()) {
						profileMatches = false // Kind mismatch, skip drift detection for this resource
					}
					if profileName != "" && profileName != resourceObj.GetName() {
						profileMatches = false // Name mismatch, skip drift detection for this resource
					}
					if profileNamespace != "" && profileNamespace != resourceObj.GetNamespace() {
						profileMatches = false // Namespace mismatch, skip drift detection for this resource
					}
				}
			}

			if profileMatches {
				fixes := DetectProfileDrift(rawManifest, containerProfile, workloadKind, containerName, rfi.DocumentIndex)
				for _, fix := range fixes {
					rfi.YamlExpressions[fix.YamlExpression] = armotypes.FixPath{Path: fix.YamlExpression, Value: ""}
				}
			}
		}

		if len(rfi.YamlExpressions) > 0 {
			resourcesToFix = append(resourcesToFix, rfi)
		}
	}

	return h.dropWrappedResources(ctx, resourcesToFix, resourcesPerFile)
}

// dropWrappedResources removes resources whose fix paths would not resolve
// against the document they were read from. A fix path is relative to its own
// resource, but the expression is evaluated at the document root, so the two
// only agree when the document is the resource. A manifest that wraps several
// resources in one document, kind: List being the usual case, breaks that: the
// paths are written to the wrapper and the file gains a spec block belonging to
// none of them.
//
// A file yielding fewer documents than the resources read from it is wrapped.
// The count comes from every resource the scan recorded, not from the failing
// ones: a List whose other members passed is still a List.  Genuine
// multi-document YAML has one document per resource and is untouched.
func (h *FixHandler) dropWrappedResources(ctx context.Context, resourcesToFix []ResourceFixInfo, resourcesPerFile map[string]int) []ResourceFixInfo {
	wrapped := make(map[string]bool, len(resourcesPerFile))
	for i := range resourcesToFix {
		// Multi-document wrapping is a property of a manifest file. An
		// in-memory resource has none, and its empty FilePath would otherwise
		// key every cluster resource together.
		if resourcesToFix[i].inMemory {
			continue
		}
		filePath := resourcesToFix[i].FilePath
		resources := resourcesPerFile[resourcesToFix[i].fileKey]
		if _, checked := wrapped[filePath]; checked || resources < 2 {
			continue
		}
		documents, err := countDocuments(ctx, filePath)
		if err != nil {
			// Leave it to the apply step, which reports the parse error itself.
			continue
		}
		wrapped[filePath] = documents < resources
	}

	kept := make([]ResourceFixInfo, 0, len(resourcesToFix))
	for i := range resourcesToFix {
		rfi := resourcesToFix[i]
		if !wrapped[rfi.FilePath] {
			kept = append(kept, rfi)
			continue
		}

		h.fixedControlsCount -= rfi.fixedCount
		for _, unfixed := range rfi.failedControls {
			unfixed.Reason = "skipped: the file declares several resources in one document"
			h.unfixedControls = append(h.unfixedControls, unfixed)
		}
	}
	return kept
}

// PrepareHelmSuggestions collects fix guidance for resources whose Source is a
// Helm chart. We never auto-edit template files for these: the fix paths are
// keyed against rendered YAML, and the previous attempts at mapping rendered
// lines back to template lines (#1215/#1551/#1620/#1628) all foundered on
// range, conditionals, whitespace trimming, and partials. Instead we surface
// the rule's intent plus the .Values.* keys the template statically reads, so
// the user can edit values.yaml themselves.
func (h *FixHandler) PrepareHelmSuggestions(ctx context.Context) []HelmFixSuggestion {
	resourceIdToResource := h.buildResourcesMap()
	suggestions := make([]HelmFixSuggestion, 0)

	for _, result := range h.reportObj.Results {
		if !result.GetStatus(nil).IsFailed() {
			continue
		}
		resourceObj := resourceIdToResource[result.ResourceID]
		if resourceObj == nil || resourceObj.Source == nil {
			continue
		}
		if resourceObj.Source.FileType != reporthandling.SourceTypeHelmChart {
			continue
		}

		var fixPaths []armotypes.FixPath
		for i := range result.AssociatedControls {
			ac := &result.AssociatedControls[i]
			if !ac.GetStatus(nil).IsFailed() {
				continue
			}
			for _, rule := range ac.ResourceAssociatedRules {
				if !rule.GetStatus(nil).IsFailed() {
					continue
				}
				for _, rp := range rule.Paths {
					if rp.FixPath.Path == "" {
						continue
					}
					if strings.HasPrefix(rp.FixPath.Value, UserValuePrefix) && h.fixInfo.SkipUserValues {
						continue
					}
					fixPaths = append(fixPaths, rp.FixPath)
				}
			}
		}
		if len(fixPaths) == 0 {
			continue
		}

		suggestions = append(suggestions, HelmFixSuggestion{
			Resource:     resourceObj,
			ChartPath:    resourceObj.Source.HelmPath,
			ChartName:    resourceObj.Source.HelmChartName,
			TemplateFile: resourceObj.Source.HelmTemplateFile,
			ValuesPaths:  resourceObj.Source.HelmValuesPaths,
			FixPaths:     fixPaths,
		})
	}
	return suggestions
}

// PrintHelmSuggestions renders the Helm fix guidance to the logger. It is
// always print-only — we never write edits for Helm sources because we cannot
// guarantee the .Values key for a given fix path. The user opens values.yaml
// and applies the change deliberately.
func (h *FixHandler) PrintHelmSuggestions(suggestions []HelmFixSuggestion) {
	if len(suggestions) == 0 {
		return
	}
	var sb strings.Builder
	sb.WriteString("\nHelm-rendered resources cannot be patched in place. Suggested values.yaml edits:\n\n")
	for _, s := range suggestions {
		fmt.Fprintf(&sb, "Chart: %s (%s)\n", s.ChartName, s.ChartPath)
		if s.TemplateFile != "" {
			fmt.Fprintf(&sb, "Template: %s\n", s.TemplateFile)
		}
		fmt.Fprintf(&sb, "Resource: %s/%s\n", s.Resource.GetKind(), s.Resource.GetName())
		sb.WriteString("Required changes (rendered-YAML paths):\n")
		for i, fp := range s.FixPaths {
			fmt.Fprintf(&sb, "\t%d) %s = %s\n", i+1, fp.Path, fp.Value)
		}
		if len(s.ValuesPaths) > 0 {
			sb.WriteString("Candidate .Values keys referenced by this template:\n")
			for _, v := range s.ValuesPaths {
				fmt.Fprintf(&sb, "\t- .Values.%s\n", v)
			}
			sb.WriteString("Edit one of these in values.yaml to satisfy the change above.\n")
		} else {
			sb.WriteString("(No .Values.* references could be statically traced for this template — edit the template directly.)\n")
		}
		sb.WriteString("\n------\n")
	}
	logger.L().Info(sb.String())
}

// UnfixedControls returns the failed (resource, control) tuples discovered during
// the most recent call to PrepareResourcesToFix that the fixer did not auto-remediate.
func (h *FixHandler) UnfixedControls() []UnfixedControl {
	out := make([]UnfixedControl, len(h.unfixedControls))
	copy(out, h.unfixedControls)
	return out
}

// FixedControlsCount returns the number of failed (resource, control) tuples that
// the fixer produced at least one yaml edit for during the most recent call to
// PrepareResourcesToFix.
func (h *FixHandler) FixedControlsCount() int {
	return h.fixedControlsCount
}

// Phase tells PrintUnfixedControls whether the fixer has already written the
// planned changes to disk or is still in a planning state (dry-run, declined
// confirm, partial apply). The summary line phrases the verb accordingly.
type Phase int

const (
	// PhasePlanned: fixes have been planned but not (fully) written. Use for
	// --dry-run, declined confirm, and partial-apply paths.
	PhasePlanned Phase = iota
	// PhaseApplied: every planned fix was successfully written to disk.
	PhaseApplied
)

// dedupUnfixedControls returns a deduplicated copy of the unfixed controls
// slice, using ControlID|Kind/Name|FilePath as the dedup key.
func dedupUnfixedControls(controls []UnfixedControl) []UnfixedControl {
	seen := make(map[string]bool, len(controls))
	out := make([]UnfixedControl, 0, len(controls))
	for _, u := range controls {
		key := u.ControlID + "|" + u.ResourceKind + "/" + u.ResourceName + "|" + u.FilePath
		if seen[key] {
			continue
		}
		seen[key] = true
		out = append(out, u)
	}
	return out
}

// PrintUnfixedControls logs the failed (resource, control) tuples that require
// manual remediation, deduplicating entries across multiple identical failures.
// The verb on the summary line reflects phase: "Auto-fixed" only when every
// planned fix was actually written; otherwise "Would auto-fix".
func (h *FixHandler) PrintUnfixedControls(phase Phase) {
	if len(h.unfixedControls) == 0 {
		return
	}

	deduped := dedupUnfixedControls(h.unfixedControls)
	var sb strings.Builder
	totalFailed := h.fixedControlsCount + len(deduped)
	verb := "Would auto-fix"
	if phase == PhaseApplied {
		verb = "Auto-fixed"
	}
	fmt.Fprintf(&sb, "%s %d of %d flagged control instances. The following require manual remediation:\n",
		verb, h.fixedControlsCount, totalFailed)

	for _, u := range deduped {
		location := u.FilePath
		if location == "" {
			location = "<unknown>"
		}
		fmt.Fprintf(&sb, "  - %s %s on %s/%s (%s) — %s\n",
			u.ControlID, u.ControlName, u.ResourceKind, u.ResourceName, location, u.Reason)
	}

	logger.L().Warning(sb.String())
}

func (h *FixHandler) PrintExpectedChanges(resourcesToFix []ResourceFixInfo) {
	var sb strings.Builder
	sb.WriteString("The following changes will be applied:\n")

	for _, resourceFixInfo := range resourcesToFix {
		// A cluster resource has no file. Printing an empty "File:" line reads
		// as a bug, so name where the resource actually came from instead.
		switch {
		case resourceFixInfo.inMemory && resourceFixInfo.Resource.GetNamespace() != "":
			fmt.Fprintf(&sb, "Source: cluster, namespace %s\n", resourceFixInfo.Resource.GetNamespace())
		case resourceFixInfo.inMemory:
			sb.WriteString("Source: cluster\n")
		default:
			fmt.Fprintf(&sb, "File: %s\n", resourceFixInfo.FilePath)
		}
		fmt.Fprintf(&sb, "Resource: %s\n", resourceFixInfo.Resource.GetName())
		fmt.Fprintf(&sb, "Kind: %s\n", resourceFixInfo.Resource.GetKind())
		sb.WriteString("Changes:\n")

		i := 1
		for _, fixPath := range resourceFixInfo.YamlExpressions {
			fmt.Fprintf(&sb, "\t%d) %s = %s\n", i, fixPath.Path, fixPath.Value)
			i++
		}
		sb.WriteString("\n------\n")
	}

	logger.L().Info(sb.String())
}

func (h *FixHandler) ApplyChanges(ctx context.Context, resourcesToFix []ResourceFixInfo) (int, []error) {
	updatedFiles := make(map[string]bool)
	errors := make([]error, 0)

	fileYamlExpressions := h.getFileYamlExpressions(resourcesToFix)

	for filepath, yamlExpression := range fileYamlExpressions {
		fileAsString, err := GetFileString(filepath)

		if err != nil {
			errors = append(errors, err)
			continue
		}

		fixedContent, err := applyFixToFileContent(ctx, filepath, fileAsString, yamlExpression)

		if err != nil {
			errors = append(errors, fmt.Errorf("failed to fix file %s: %w ", filepath, err))
			continue
		}

		if err := writeFixesToFile(filepath, fixedContent); err != nil {
			logger.L().Ctx(ctx).Warning(fmt.Sprintf("Failed to write fixes to file %s, %v", filepath, err.Error()))
			errors = append(errors, err)
			continue
		}

		updatedFiles[filepath] = true
	}

	return len(updatedFiles), errors
}

// isPathContained reports whether target resolves to a path inside base,
// preventing a resource path from the (untrusted) scan report from escaping
// the local scan directory. Both operands are resolved with
// filepath.EvalSymlinks before comparing: filepath.Rel alone is purely
// lexical and never touches the filesystem, so a symlink inside base that
// points outside it - or a dangling symlink - would otherwise be reported as
// "contained" even though the file it actually reads/writes lives elsewhere,
// or doesn't resolve at all. Resolution failure (nonexistent path, dangling
// symlink, permission error) is treated as not contained rather than
// silently allowed.
func isPathContained(base, target string) bool {
	resolvedBase, err := filepath.EvalSymlinks(base)
	if err != nil {
		return false
	}
	resolvedTarget, err := filepath.EvalSymlinks(target)
	if err != nil {
		return false
	}
	rel, err := filepath.Rel(resolvedBase, resolvedTarget)
	if err != nil {
		return false
	}
	return rel != ".." && !strings.HasPrefix(rel, ".."+string(filepath.Separator))
}

// sanitizeForLog strips ASCII control characters (including \r and \n) from
// report-derived strings before they are interpolated into a log message.
// The default CLI logger prints messages as plain text, so an
// attacker-controlled resource path or resource ID containing "\r\n" could
// otherwise forge additional, spoofed-looking log lines.
func sanitizeForLog(s string) string {
	return strings.Map(func(r rune) rune {
		if r < 0x20 || r == 0x7f {
			return -1
		}
		return r
	}, s)
}

func (h *FixHandler) getFilePathAndIndex(filePathWithIndex string) (filePath string, documentIndex int, err error) {
	volume := filepath.VolumeName(filePathWithIndex)
	pathWithoutVolume := filePathWithIndex[len(volume):]

	lastColon := strings.LastIndex(pathWithoutVolume, ":")
	if lastColon == -1 {
		return "", 0, fmt.Errorf("expected to find ':' in file path")
	}
	lastColon += len(volume)

	filePath = filePathWithIndex[:lastColon]
	indexStr := filePathWithIndex[lastColon+1:]

	documentIndex, err = strconv.Atoi(indexStr)
	if err != nil {
		return "", 0, err
	}

	return filePath, documentIndex, nil
}

func ApplyFixToContent(ctx context.Context, yamlAsString, yamlExpression string) (fixedString string, err error) {
	yamlAsString = sanitizeYaml(yamlAsString)
	newline := determineNewlineSeparator(yamlAsString)

	yamlLines := strings.Split(yamlAsString, newline)

	originalRootNodes, err := decodeDocumentRoots(yamlAsString)

	if err != nil {
		return "", err
	}

	fixedRootNodes, err := getFixedNodes(ctx, yamlAsString, yamlExpression)

	if err != nil {
		return "", err
	}

	fixInfo, err := getFixInfo(ctx, originalRootNodes, fixedRootNodes)
	if err != nil {
		return "", err
	}

	fixedYamlLines := getFixedYamlLines(yamlLines, fixInfo, newline)

	fixedString = getStringFromSlice(fixedYamlLines, newline)
	fixedString = revertSanitizeYaml(fixedString)

	return fixedString, nil
}

// isFixableSourceType reports whether the scan parsed a file the fix engine can
// rewrite. Helm-rendered resources carry their own type and are handled by
// PrepareHelmSuggestions instead.
func isFixableSourceType(fileType string) bool {
	return fileType == reporthandling.SourceTypeYaml || fileType == reporthandling.SourceTypeJson
}

// applyFixToFileContent rewrites one file, keeping it in the format it was
// written in. Emitting YAML into a .json manifest would break every tool that
// reads it back.
func applyFixToFileContent(ctx context.Context, filePath, content, yamlExpression string) (string, error) {
	if isJSONSource(filePath) {
		return applyFixToJSONContent(ctx, content, yamlExpression)
	}
	return ApplyFixToContent(ctx, content, yamlExpression)
}

func (h *FixHandler) getFileYamlExpressions(resourcesToFix []ResourceFixInfo) map[string]string {
	fileYamlExpressions := make(map[string]string, 0)
	for _, toPin := range resourcesToFix {
		resourceToFix := toPin

		// An in-memory resource has no FilePath. Grouping it here would collapse
		// every cluster resource under the empty key and hand ApplyChanges a
		// file to write that does not exist.
		if resourceToFix.inMemory {
			continue
		}

		singleExpression := reduceYamlExpressions(&resourceToFix)
		resourceFilePath := resourceToFix.FilePath

		if _, pathExistsInMap := fileYamlExpressions[resourceFilePath]; !pathExistsInMap {
			fileYamlExpressions[resourceFilePath] = singleExpression
		} else {
			fileYamlExpressions[resourceFilePath] = joinStrings(fileYamlExpressions[resourceFilePath], " | ", singleExpression)
		}

	}

	return fileYamlExpressions
}

// plannedFix is one planned YAML edit's location and the value it writes
// there, kept together so a caller can tell not just that a planned edit
// touches a given path, but whether it writes the value another control's
// check actually expected to find (see controlIsCoveredByPlannedPaths).
type plannedFix struct {
	Path  string
	Value string
}

// plannedPathsFromExpressions returns every non-empty (Path, Value) pair
// from a YamlExpressions map, used by the unfixed-control reconciliation
// pass to test whether a control's failed paths are covered by some planned
// edit. exprs' own keys (the yaml expression strings) are already unique,
// so no further dedup is applied here: two entries can legitimately share a
// Path with different Values (two controls each owning their own concrete
// FixPath at the same location), and collapsing those to one by Path alone
// would silently discard whichever Value the map's (unordered) iteration
// happened to visit second -- now that Value is load-bearing for
// controlIsCoveredByPlannedPaths' coverage decision, that would reintroduce
// the exact class of bug this reconciliation pass exists to avoid, just
// nondeterministically. controlIsCoveredByPlannedPaths' own inner loop
// already checks every entry and only accepts an actual match, so keeping
// duplicates is harmless.
func plannedPathsFromExpressions(exprs map[string]armotypes.FixPath) []plannedFix {
	if len(exprs) == 0 {
		return nil
	}
	out := make([]plannedFix, 0, len(exprs))
	for _, fp := range exprs {
		if fp.Path == "" {
			continue
		}
		out = append(out, plannedFix{Path: fp.Path, Value: fp.Value})
	}
	return out
}

// normalizeFailedPath strips an "=<expected>" suffix that some FailedPath
// values carry to encode the value the check expected (e.g.
// "spec.…runAsNonRoot=true"). The reconciliation pass compares pure YAML
// paths, so the suffix must not participate in the segment-boundary check.
func normalizeFailedPath(p string) string {
	if before, _, ok := strings.Cut(p, "="); ok {
		return before
	}
	return p
}

// expectedValueSuffix extracts the "<expected>" part of a raw path value
// like "spec.…runAsNonRoot=true" -- the same suffix normalizeFailedPath
// discards. ok is false when p carries no "=" at all, meaning the check
// recorded no specific expected value to compare against.
func expectedValueSuffix(p string) (value string, ok bool) {
	_, after, found := strings.Cut(p, "=")
	if !found {
		return "", false
	}
	return after, true
}

// yamlValuesEqual reports whether two raw fix-value strings represent the
// same YAML value, tolerating formatting differences (quoting, spacing,
// key order) a literal string comparison would wrongly treat as different.
// Either string failing to parse falls back to a literal comparison rather
// than silently treating an unparsable value as a match -- callers only
// reach here to decide whether to REFUSE a promotion, so being unable to
// parse a value must not accidentally make two different-looking strings
// compare equal.
func yamlValuesEqual(a, b string) bool {
	var av, bv any
	if err := yaml.Unmarshal([]byte(a), &av); err != nil {
		return a == b
	}
	if err := yaml.Unmarshal([]byte(b), &bv); err != nil {
		return a == b
	}
	return reflect.DeepEqual(av, bv)
}

// yamlPathCovers reports whether setting `planned` necessarily satisfies a
// check that observed `failed`. Coverage holds when planned == failed, or
// planned is an ancestor of failed on YAML-segment boundaries — segments are
// separated by '.' or '['. String prefix alone is not enough: "spec.host" must
// not be treated as covering "spec.hostNetwork". Callers must pass a
// normalized `failed` (see normalizeFailedPath) since FailedPath values may
// carry "=<expected>" suffixes.
func yamlPathCovers(planned, failed string) bool {
	if planned == "" || failed == "" {
		return false
	}
	if planned == failed {
		return true
	}
	if !strings.HasPrefix(failed, planned) {
		return false
	}
	next := failed[len(planned)]
	return next == '.' || next == '['
}

// actionableLocation returns the normalized YAML location a path entry
// describes, and the raw string it was derived from (which may still carry
// an "=<expected>" suffix normalizeFailedPath stripped from location),
// regardless of which remediation field it was stored in. PosturePaths
// entries carry exactly one of FailedPath / DeletePath / ReviewPath / FixPath
// in practice (see appendPaths in opa-utils), so taking the first non-empty
// one yields the location the check was actually pointing at. Callers that
// need the value the check expected use raw with expectedValueSuffix.
func actionableLocation(p armotypes.PosturePaths) (location, raw string) {
	if p.FailedPath != "" {
		return normalizeFailedPath(p.FailedPath), p.FailedPath
	}
	if p.DeletePath != "" {
		return normalizeFailedPath(p.DeletePath), p.DeletePath
	}
	if p.ReviewPath != "" {
		return normalizeFailedPath(p.ReviewPath), p.ReviewPath
	}
	if p.FixPath.Path != "" {
		return p.FixPath.Path, p.FixPath.Path
	}
	return "", ""
}

// controlIsCoveredByPlannedPaths reports whether every actionable path entry
// on the control's failed rules is covered by some planned FixPath. Every
// entry counts — FailedPath, DeletePath, and ReviewPath alike — so a control
// that requires (for example) deleting `spec.hostNetwork` cannot be promoted
// just because an unrelated FailedPath happens to overlap with a planned
// edit. A control whose rules carry no actionable locations at all is not
// promoted either (nothing concrete to match against).
//
// An exact path match (not merely an ancestor) is further required to write
// the same value the failed check expected, when that check recorded one
// (a FailedPath's "=<expected>" suffix): path overlap alone does not prove
// a different control's fix actually satisfies this check, only that it
// touches the same field. Two controls checking the same field for two
// different concrete values (e.g. one wants capabilities.drop == ["ALL"],
// another wants it == ["SYS_ADMIN","NET_ADMIN"]) must not promote each
// other. An ancestor match (the planned edit replaces a whole subtree the
// failed path lives inside) still counts as covered without a value check:
// verifying a specific leaf's resulting value inside an arbitrarily
// structured subtree write is not attempted here.
func controlIsCoveredByPlannedPaths(ac *resourcesresults.ResourceAssociatedControl, plannedPaths []plannedFix) bool {
	sawActionablePath := false
	for _, rule := range ac.ResourceAssociatedRules {
		if !rule.GetStatus(nil).IsFailed() {
			continue
		}
		for _, p := range rule.Paths {
			loc, raw := actionableLocation(p)
			if loc == "" {
				continue
			}
			sawActionablePath = true
			expected, hasExpected := expectedValueSuffix(raw)
			covered := false
			for _, planned := range plannedPaths {
				if !yamlPathCovers(planned.Path, loc) {
					continue
				}
				if planned.Path == loc && hasExpected && !yamlValuesEqual(planned.Value, expected) {
					// Same field, but this planned fix writes a value the
					// failed check did not expect: overlap alone does not
					// prove the check would now pass.
					continue
				}
				covered = true
				break
			}
			if !covered {
				return false
			}
		}
	}
	return sawActionablePath
}

// addYamlExpressionsFromResourceAssociatedControl appends one yaml expression
// for every failed-rule FixPath that produces a concrete remediation. It returns
// per-path counters so callers can distinguish fully-fixable controls from
// partially-fixable controls (some paths fixable, some skipped/unfixable) from
// fully-unfixable ones. skippedReasons describes paths that could not be
// auto-remediated, in classification order.
func (rfi *ResourceFixInfo) addYamlExpressionsFromResourceAssociatedControl(documentIndex int, ac *resourcesresults.ResourceAssociatedControl, skipUserValues bool) (added int, skippedReasons []string) {
	for _, rule := range ac.ResourceAssociatedRules {
		if !rule.GetStatus(nil).IsFailed() {
			continue
		}

		ruleHadFixPath := false
		for _, rulePaths := range rule.Paths {
			if rulePaths.FixPath.Path == "" {
				continue
			}
			ruleHadFixPath = true

			if strings.HasPrefix(rulePaths.FixPath.Value, UserValuePrefix) && skipUserValues {
				skippedReasons = append(skippedReasons, "skipped: auto-fix requires a user-supplied value (--skip-user-values is set)")
				continue
			}

			yamlExpression := FixPathToValidYamlExpression(rulePaths.FixPath.Path, rulePaths.FixPath.Value, documentIndex)
			if yamlExpression == "" {
				logger.L().Debug("skipping fix path that is not a plain yaml path",
					helpers.String("fixPath", sanitizeForLog(rulePaths.FixPath.Path)))
				skippedReasons = append(skippedReasons, "skipped: fix path is not a plain yaml path")
				continue
			}
			rfi.YamlExpressions[yamlExpression] = rulePaths.FixPath
			added++
		}

		// A failed rule with no FixPath at all is a check we don't know how to
		// remediate automatically — still surface it as needing manual work.
		if !ruleHadFixPath {
			skippedReasons = append(skippedReasons, "no auto-fix available for this control")
		}
	}
	return added, skippedReasons
}

// reduceYamlExpressions reduces the number of yaml expressions to a single one
func reduceYamlExpressions(resource *ResourceFixInfo) string {
	expressions := make([]string, 0, len(resource.YamlExpressions))
	for expr := range resource.YamlExpressions {
		expressions = append(expressions, expr)
	}
	sort.Strings(expressions)
	return strings.Join(expressions, " | ")
}

// safeFixPath matches the subset of yq's expression grammar that a fix path is
// allowed to use: dot-separated keys — bare or double-quoted — each optionally
// followed by list indices. Everything else yq accepts in that position
// (pipes, parentheses, comparison and assignment operators, function calls
// such as strenv() or load_str()) is expression syntax, not a path.
var safeFixPath = regexp.MustCompile(`^(?:[A-Za-z0-9_/-]+|"[^"\\]*")(?:\[(?:\d+|\*)\])*(?:\.(?:[A-Za-z0-9_/-]+|"[^"\\]*")(?:\[(?:\d+|\*)\])*)*$`)

// safeSequenceValue matches a flow sequence of plain scalars, which is the
// only shape of value that may be spliced into the expression unquoted.
var safeSequenceValue = regexp.MustCompile(`^\[\s*(?:(?:"[^"\\]*"|-?\d+(?:\.\d+)?|true|false)(?:\s*,\s*(?:"[^"\\]*"|-?\d+(?:\.\d+)?|true|false))*\s*)?\]$`)

// FixPathToValidYamlExpression builds the yq expression that writes value at
// fixPath in document documentIndexInYaml. It returns an empty string when
// fixPath is not a plain yaml path, and callers must skip such paths.
//
// Both operands come from the report file, which `kubescape fix` treats as
// untrusted input (hence --base-path), and both are spliced into an expression
// that yq then evaluates. A path such as
//
//	metadata.annotations.leak |= strenv(KUBESCAPE_ACCESS_KEY) | select(di==0).spec.hostNetwork
//
// parses as valid yq and makes `fix` copy an environment variable — or, via
// load_str(), any local file — into the user's manifest, which is then written
// back to disk. Validating both operands against a path/scalar grammar keeps a
// crafted report from steering the expression.
func FixPathToValidYamlExpression(fixPath, value string, documentIndexInYaml int) string {
	if !safeFixPath.MatchString(fixPath) {
		return ""
	}

	isStringValue := true
	if _, err := strconv.ParseBool(value); err == nil {
		isStringValue = false
	} else if f, err := strconv.ParseFloat(value, 64); err == nil && !math.IsNaN(f) && !math.IsInf(f, 0) {
		isStringValue = false
	} else if _, err := strconv.Atoi(value); err == nil {
		isStringValue = false
	}

	// Strings should be quoted. Escape only `"` — yq's expression lexer
	// (lexer_participle.go stringValue) unescapes \" and nothing else, so any
	// other Go-style escape would be written to the file literally.
	//
	// Do not quote if the value is meant to be a YAML sequence — but only when
	// it really is one. Looking at the brackets alone is not enough: yq reads
	// `[strenv(SECRET)]` as a collect operator around a function call, and
	// `[] | (...) | [1]` as a pipeline, so both would evaluate rather than land
	// as a literal sequence. Anything that is not a sequence of plain scalars
	// is quoted like any other string value.
	if isStringValue && !safeSequenceValue.MatchString(value) {
		value = `"` + strings.ReplaceAll(value, `"`, `\"`) + `"`
	}

	// select document index and add a dot for the root node
	return fmt.Sprintf("select(di==%d).%s |= %s", documentIndexInYaml, fixPath, value)
}

func joinStrings(inputStrings ...string) string {
	return strings.Join(inputStrings, "")
}

func GetFileString(path string) (string, error) {
	bytes, err := os.ReadFile(filepath.Clean(path))

	if err != nil {
		return "", fmt.Errorf("error reading file %s", path)
	}

	return string(bytes), nil
}

func writeFixesToFile(path, content string) error {
	perm := os.FileMode(0644)
	if info, err := os.Stat(filepath.Clean(path)); err == nil {
		perm = info.Mode().Perm()
	} else if !os.IsNotExist(err) {
		return fmt.Errorf("error reading file permissions: %w", err)
	}

	file, err := os.OpenFile(filepath.Clean(path), os.O_WRONLY|os.O_CREATE|os.O_TRUNC, perm)
	if err != nil {
		return fmt.Errorf("error writing fixes to file: %w", err)
	}

	return writeAndClose(file, content)
}

// writeStringCloser is the subset of *os.File that writeAndClose needs to
// write the fixed manifest and close the file, checking both errors. It
// exists so a fake can simulate a Close-time failure deterministically in
// tests: reproducing that with a real file would require an actually faulty
// filesystem (e.g. NFS, which can accept a Write into its client-side buffer
// and only report ENOSPC when the buffer is flushed at Close), which isn't
// something a portable unit test can arrange.
type writeStringCloser interface {
	WriteString(s string) (int, error)
	Close() error
}

// writeAndClose writes content and closes file, checking both errors instead
// of closing via defer. A write can appear to succeed while the underlying
// filesystem only reports a real failure (e.g. out of space) when the file is
// closed and its buffered data is finally flushed - discarding that error, as
// a deferred Close() would, reports success for a fix that was silently never
// written to disk.
func writeAndClose(file writeStringCloser, content string) error {
	if _, err := file.WriteString(content); err != nil {
		_ = file.Close() // best-effort; the write error is already being reported
		return fmt.Errorf("error writing fixes to file: %w", err)
	}

	if err := file.Close(); err != nil {
		return fmt.Errorf("error writing fixes to file: failed to flush: %w", err)
	}

	return nil
}

func determineNewlineSeparator(contents string) string {
	switch {
	case strings.Contains(contents, windowsNewline):
		return windowsNewline
	default:
		return unixNewline
	}
}

// sanitizeYaml receives a YAML file as a string, sanitizes it and returns the result
//
// Callers should remember to call the corresponding revertSanitizeYaml function.
//
// It applies the following sanitization:
//
// - Since `yaml/v3` fails to serialize documents starting with a document
// separator, we comment it out to be compatible.
func sanitizeYaml(fileAsString string) string {
	if strings.HasPrefix(fileAsString, "---") {
		fileAsString = "# " + fileAsString
	}
	return fileAsString
}

// revertSanitizeYaml receives a sanitized YAML file as a string and reverts the applied sanitization
//
// For sanitization details, refer to the sanitizeYaml() function.
func revertSanitizeYaml(fixedYamlString string) string {
	if strings.HasPrefix(fixedYamlString, "# ---") {
		fixedYamlString = fixedYamlString[2:]
	}
	return fixedYamlString
}
