package reportcrypto

import (
	"crypto/rand"
	"encoding/binary"
	"errors"
	"io"
)

const (
	// bindingSize is the length of the per-report binding value. It is a
	// public, non-secret label - it is stored in cleartext in the wrapped-DEK
	// envelope - so it only has to be long enough that two independently
	// generated reports never collide.
	bindingSize = 16

	// aadContext is the outermost domain-separation tag mixed into every piece
	// of additional authenticated data this package produces. It exists so
	// that AAD generated here can never coincide with AAD generated by some
	// other Kubescape subsystem that happens to use the same domain names.
	aadContext = "kubescape.report.aad.v1"

	// aadDomainDEK and aadDomainField name the class of plaintext a ciphertext
	// holds. Binding the class means a wrapped DEK and a report field are not
	// interchangeable envelopes even when an attacker can supply both.
	//
	// Adding a domain is the intended way to narrow this further: a new
	// constant here plus the matching call on the decrypt side binds that
	// field class without touching the envelope format.
	aadDomainDEK   = "dek"
	aadDomainField = "field"
)

// ErrNilReportKey is returned when an operation needs a report key and none was
// supplied. It is distinct from a key that merely holds an invalid DEK, which
// ValidateDEK reports.
var ErrNilReportKey = errors.New("report key is nil")

// ReportKey is the data-encryption key of one report together with the binding
// value that every ciphertext in that report is authenticated against.
//
// The two travel together because they are only meaningful together: a DEK
// tells you whether a ciphertext decrypts, and the binding tells you whether it
// decrypts *here*. Keeping them in one value is what stops a call site from
// silently sealing a field with no associated data, which is exactly how
// ciphertexts became interchangeable in the first place.
//
// A key with a nil binding is "unbound": it seals and opens with no associated
// data, which is the format every release before bindings existed produced.
// Unbound keys are only ever created when reading such a report, never when
// writing a new one.
type ReportKey struct {
	dek     []byte
	binding []byte
}

// NewReportKey adopts an existing DEK and generates the binding that ties every
// ciphertext of one report to that report.
//
// The DEK is referenced, not copied, so the caller keeps ownership of the bytes
// and remains responsible for zeroing them; Zero on the returned key does the
// same job for callers that hand the DEK over entirely.
func NewReportKey(dek []byte) (*ReportKey, error) {
	if err := ValidateDEK(dek); err != nil {
		return nil, err
	}

	binding := make([]byte, bindingSize)
	if _, err := io.ReadFull(rand.Reader, binding); err != nil {
		return nil, err
	}

	return &ReportKey{dek: dek, binding: binding}, nil
}

// UnboundReportKey adopts a DEK with no binding, reproducing the pre-binding
// envelope format exactly.
//
// It is the reader for reports written before this change and the compatibility
// shim behind the deprecated bare-DEK helpers. New reports must come from
// NewReportKey, so that the binding is never omitted by accident.
//
// The DEK is validated lazily, when it is first used, matching EncryptString
// and DecryptString.
func UnboundReportKey(dek []byte) *ReportKey {
	return &ReportKey{dek: dek}
}

// DEK returns the underlying data-encryption key.
func (k *ReportKey) DEK() []byte {
	if k == nil {
		return nil
	}

	return k.dek
}

// Binding returns the per-report binding value, or nil for an unbound key.
func (k *ReportKey) Binding() []byte {
	if k == nil {
		return nil
	}

	return k.binding
}

// IsBound reports whether ciphertexts sealed with this key carry associated
// data.
func (k *ReportKey) IsBound() bool {
	return k != nil && k.binding != nil
}

// Zero wipes the data-encryption key.
//
// The binding is deliberately left intact: it is written to the report in
// cleartext, so it is not a secret and clearing it would only make a
// partially-zeroed key look usable.
func (k *ReportKey) Zero() {
	if k == nil {
		return
	}

	zeroBytes(k.dek)
}

// EncryptString seals plaintext as a report field, binding the ciphertext to
// this report.
func (k *ReportKey) EncryptString(plaintext string) (string, error) {
	if k == nil {
		return "", ErrNilReportKey
	}

	return sealString(plaintext, k.dek, buildAAD(aadDomainField, k.binding))
}

// DecryptString opens a report field sealed by EncryptString.
//
// A ciphertext lifted from a different report fails here rather than decrypting
// cleanly, because its binding does not match this report's.
func (k *ReportKey) DecryptString(ciphertext string) (string, error) {
	if k == nil {
		return "", ErrNilReportKey
	}

	return openString(ciphertext, k.dek, buildAAD(aadDomainField, k.binding))
}

// buildAAD renders the additional authenticated data for one ciphertext class.
//
// Every component is length-prefixed rather than concatenated. Plain
// concatenation is ambiguous - ("de", "k") and ("d", "ek") render identically -
// and an ambiguous encoding makes the AAD decorative rather than binding, which
// is the same class of mistake as passing nil.
//
// An unbound key yields nil, which is what AES-GCM was called with before
// bindings existed. That is what keeps reports written by earlier releases
// readable.
func buildAAD(domain string, binding []byte) []byte {
	if binding == nil {
		return nil
	}

	aad := make([]byte, 0, 12+len(aadContext)+len(domain)+len(binding))
	aad = appendLengthPrefixed(aad, []byte(aadContext))
	aad = appendLengthPrefixed(aad, []byte(domain))
	aad = appendLengthPrefixed(aad, binding)

	return aad
}

// appendLengthPrefixed is only ever called with aadContext, an AAD domain
// literal, or a bindingSize-length binding - all fixed, well under 4 GiB - so
// the length cannot overflow uint32.
func appendLengthPrefixed(dst []byte, value []byte) []byte {
	dst = binary.BigEndian.AppendUint32(dst, uint32(len(value))) // #nosec G115 -- length of a fixed-size internal value, never near uint32 range

	return append(dst, value...)
}
