apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: rules.spdx.softwarecomposition.kubescape.io
spec:
  group: spdx.softwarecomposition.kubescape.io
  versions:
    - name: v1alpha1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            rego:
              type: string
            blob:
              x-kubernetes-preserve-unknown-fields: true
  scope: Cluster
  names:
    plural: rules
    singular: rule
    kind: Rule
    shortNames:
    - rule