{{- if .Values.configMap.create -}}
kind: ConfigMap
apiVersion: v1
metadata:
  name: {{ include "kubescape.fullname" . }}-configmap
  labels:
    {{- include "kubescape.labels" . | nindent 4 }}
data:
  config.json: |
    {
      "customerGUID": "{{ .Values.configMap.params.customerGUID }}",
      "clusterName": "{{ .Values.configMap.params.clusterName }}"
    }
{{- end }}
