name: publish-artifacts

on:
  workflow_call:
    inputs:
      upload_url:
        description: 'upload url'
        required: true
        type: string
      release:
        description: 'release tag'
        required: true
        type: string

jobs:
  publish-artifacts:
    name: Build and publish artifacts
    runs-on: ${{ matrix.os }}
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    strategy:
      matrix:
        os: [ubuntu-20.04, macos-latest, windows-latest]
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.19

      - name: Install MSYS2 & libgit2 (Windows)
        shell: cmd
        run: .\build.bat all
        if: matrix.os == 'windows-latest'

      - name: Install libgit2 (Linux/macOS)
        run: make libgit2
        if: matrix.os != 'windows-latest'

      - name: Build
        env:
          RELEASE: ${{ inputs.release }}
          CLIENT: release
          CGO_ENABLED: 1
        run: python3 --version && python3 build.py

      - name: Upload release assets (Windows / MacOS)
        id: upload-release-asset-win-macos
        uses: shogo82148/actions-upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ inputs.upload_url }}
          asset_path: build/${{ matrix.os }}/*
        if: matrix.os != 'ubuntu-20.04'

      - name: Upload release assets (Linux)
        id: upload-release-asset-linux
        uses: shogo82148/actions-upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ inputs.upload_url }}
          asset_path: build/ubuntu-latest/*
        if: matrix.os == 'ubuntu-20.04'

  publish-krew-plugin:
    name: Publish Krew plugin
    runs-on: ubuntu-latest
    if: "${{ github.repository_owner }} == kubescape"
    needs: publish-artifacts
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive
      - name: Update new version in krew-index
        uses: rajatjindal/krew-release-bot@v0.0.43
