name: 03-post_release
permissions: read-all
on:
  release:
    types: [published]
    branches:
      - 'master'
      - 'main'
jobs:
  post_release:
    name: Post release jobs
    runs-on: ubuntu-latest
    steps:
      - name: Digest
        uses: MCJack123/ghaction-generate-release-hashes@c03f3111b39432dde3edebe401c5a8d1ffbbf917 # ratchet:MCJack123/ghaction-generate-release-hashes@v1
        with:
          hash-type: sha1
          file-name: kubescape-release-digests
      - name: Invoke workflow to update packaging
        uses: benc-uk/workflow-dispatch@v1
        if: github.repository_owner == 'kubescape'
        with:
          workflow: release.yml
          repo: kubescape/packaging
          ref: refs/heads/main
          token: ${{ secrets.GH_PERSONAL_ACCESS_TOKEN }}
      - name: Invoke workflow to update homebrew tap
        uses: benc-uk/workflow-dispatch@v1
        if: github.repository_owner == 'kubescape'
        with:
          workflow: release.yml
          repo: kubescape/homebrew-tap
          ref: refs/heads/main
          token: ${{ secrets.GH_PERSONAL_ACCESS_TOKEN }}
      - name: Invoke workflow to update github action
        uses: benc-uk/workflow-dispatch@v1
        if: github.repository_owner == 'kubescape'
        with:
          workflow: release.yaml
          repo: kubescape/github-action
          ref: refs/heads/main
          token: ${{ secrets.GH_PERSONAL_ACCESS_TOKEN }}
