name: 04-publish_krew_plugin
permissions: read-all
on:
  push:
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+'
jobs:
  publish_krew_plugin:
    name: Publish Krew plugin
    runs-on: ubuntu-latest
    if: github.repository_owner == 'kubescape'
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive
      - name: Update new version in krew-index
        uses: rajatjindal/krew-release-bot@92da038bbf995803124a8e50ebd438b2f37bbbb0 # ratchet:rajatjindal/krew-release-bot@v0.0.43
