name: pr-checks

on:
  pull_request:
    types: [ edited, opened, synchronize, reopened ]
    branches: 
      - 'master'
      - 'main'
      - 'dev'
    paths-ignore:
      - '**.yaml'
      - '**.md'
      - '**.sh'
      - 'website/*'
      - 'examples/*'
      - 'docs/*'
      - 'build/*'
      - '.github/*'
jobs:
  test:
    uses: ./.github/workflows/00-test.yaml
    with:
      release: ${{ github.ref_name}}
      client: test
