name: a-pr-scanner
permissions:
  contents: read
  checks: read
  actions: read
  packages: read
  pull-requests: read
on:
  workflow_call:
    inputs:
      RELEASE:
        description: 'release'
        required: true
        type: string
      CLIENT:
        description: 'Client name'
        required: true
        type: string
      UNIT_TESTS_PATH:
        required: false
        type: string
        default: "./..."
      GO111MODULE:
        required: true
        type: string
      CGO_ENABLED:
        type: number
        default: 1
jobs:
  unit-tests:
    if: ${{ github.actor != 'kubescape' }}
    name: Create cross-platform build
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    runs-on: ubuntu-large
    timeout-minutes: 20
    steps:

      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          fetch-depth: 0

      - uses: actions/setup-go@b7ad1dad31e06c5925ef5d2fc7ad053ef454303e # v7.0.0
        name: Installing go
        with:
          go-version-file: go.mod

      - name: Test core pkg
        run: ${{ env.DOCKER_CMD }} go test -race -v ./...

      - name: Test cautils pkg with race detector
        env:
          CGO_ENABLED: 1
        run: ${{ env.DOCKER_CMD }} go test -v -race ./core/cautils/...

      - name: Test httphandler pkg
        run: ${{ env.DOCKER_CMD }} go test -v ./httphandler/...

      - uses: anchore/sbom-action/download-syft@3ad7283483fc7af8ff2b4ea19663c2d5ca935e26 # v0.24.2
        name: Setup Syft

      - uses: goreleaser/goreleaser-action@f06c13b6b1a9625abc9e6e439d9c05a8f2190e94 # v7.2.3
        name: Build
        with:
          distribution: goreleaser
          version: latest
          args: build --clean --snapshot --single-target
        env:
          RELEASE: ${{ inputs.RELEASE }}
          CLIENT: ${{ inputs.CLIENT }}
          CGO_ENABLED: ${{ inputs.CGO_ENABLED }}

      - name: Smoke Testing
        env:
          RELEASE: ${{ inputs.RELEASE }}
          KUBESCAPE_SKIP_UPDATE_CHECK: "true"
        run: ${{ env.DOCKER_CMD }} python3 smoke_testing/init.py ${PWD}/dist/cli_linux_amd64_v1/kubescape

      - name: golangci-lint
        continue-on-error: false
        uses: golangci/golangci-lint-action@ba0d7d2ec06a0ea1cb5fa41b2e4a3ab91d21278a # v9.3.0
        with:
          version: v2.12.2
          args: --timeout 10m
          only-new-issues: true
