name: release

on:
  push:
    tags:
    # - 'v*.*.*-rc.*' # Comment out since the re-tagging process is not yet implemented
    - 'v*.*.*'
jobs:
  test:
    uses: ./.github/workflows/00-test.yaml
    with:
      release: ${{ github.ref_name}}
      client: test
  
  # integration-test:
  #   if: ${{ label == e2e-tests }}

  # re-tag:
  #   # if tests passed, create new tag without `rc`
    
  create-release:
    uses: ./.github/workflows/01-create-release.yaml
    needs: test
    with:
      release_name: "Release ${{ github.ref_name}}"
      tag: ${{ github.ref_name}}
    secrets: inherit

  publish-artifacts:
    uses: ./.github/workflows/02-publish-artifacts.yaml
    needs: create-release
    with:
      upload_url: ${{ needs.create-release.outputs.upload_url }}
      release: "${{ github.ref_name}}"
    secrets: inherit
       

  publish-image:
    uses: ./.github/workflows/03-publish-image.yaml
    needs: create-release
    with:
      client: "image-release"
      image_name: "quay.io/${{ github.repository_owner }}/kubescape"
      image_tag: "${{ github.ref_name}}"
      support_platforms: true
      cosign: true
    secrets: inherit
