name: create release digests

on:
  release:
    types: [ published]
    branches:
    - 'master'
    - 'main'
  
jobs:
  once:
    name: Creating digests
    runs-on: ubuntu-latest
    steps:
      - name: Digest
        uses: MCJack123/ghaction-generate-release-hashes@v1
        with:
          hash-type: sha1
          file-name: kubescape-release-digests
